  trigger: none

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    buildConfiguration: 'Release'
    azureServiceConnection: 'svc_stati_web_app'
    azureAppServiceName: 'mfwebapp4567'

  steps:

  - task: UseDotNet@2
    displayName: "check dotnet avalability"
    inputs:
      packageType: 'sdk'
      version: '6.x'
      includePreviewVersions: true

  - task: UseDotNet@2
    displayName: "install dotnet"
    inputs:
      packageType: 'runtime'
      version: '6.x'
      includePreviewVersions: true
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Tests.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  - task: CmdLine@2
    inputs:
      script: |
        dir $(Build.ArtifactStagingDirectory)
        echo %cd%
  
  

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'svc_stati_web_app'
      KeyVaultName: 'staticwebappkv'
      SecretsFilter: '*'
      RunAsPreJob: true

  - task: CmdLine@2
    inputs:
      script: 'echo $(staticwebappkv) > secret.txt'


  - task: CopyFiles@2
    inputs:
      Contents: 'secret.txt'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '$(Build.ArtifactStagingDirectory)'
      azure_static_web_apps_api_token: '455e84a6564232e0957a2933432c247557c69187c34b9d7962b2053f9c5017fa4-783227df-60a5-446d-b502-9fce037142bc00f151852'

