trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  azureServiceConnection: 'svc_stati_web_app'
  azureAppServiceName: 'mfwebapp4567'

steps:
- task: UseDotNet@2
  displayName: "Check .NET availability"
  inputs:
    packageType: 'sdk'
    version: '6.x'
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: "Install .NET"
  inputs:
    packageType: 'runtime'
    version: '6.x'
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'svc_stati_web_app'
    KeyVaultName: 'staticwebappkv'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: AzureStaticWebApp@0
  inputs:
    app_location: '$(Build.ArtifactStagingDirectory)'
    output_location: '$(Build.ArtifactStagingDirectory)/output'
    api_token: '$(staticwebappkv)'
