trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  azureServiceConnection: 'Pay-As-You-Go(f510d486-a17f-44f2-a1c4-63a7186e923c)'
  azureAppServiceName: 'mfwebapp4567'

steps:

- task: UseDotNet@2
  displayName: "check dotnet avalability"
  inputs:
    packageType: 'sdk'
    version: '6.x'
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: "install dotnet"
  inputs:
    packageType: 'runtime'
    version: '6.x'
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: CmdLine@2
  inputs:
    script: |
      ls $(Build.ArtifactStagingDirectory)/project
      pwd


- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(f510d486-a17f-44f2-a1c4-63a7186e923c)'
    KeyVaultName: 'staticwebappkv'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: CmdLine@2
  inputs:
    script: 'echo $(staticwebappkv) > secret.txt'


- task: CopyFiles@2
  inputs:
    Contents: 'secret.txt'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# - task: AzureStaticWebApp@0
#   inputs:
#     azure_static_web_apps_api_token: '''$(Build.ArtifactStagingDirectory)'''

# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: ${{ variables.azureServiceConnection }}
#     appType: 'webApp'
#     WebAppName: ${{ variables.azureAppServiceName }}
#     packageForLinux: '$(build.ArtifactStagingDirectory)/s.zip'
#     enableCustomDeployment: true
#     DeploymentType: 'zipDeploy'

